---
kind: pipeline
type: docker
name: default

steps:
  - name: "Scala 2.13.0 (code coverage)"
    image: hseeberger/scala-sbt:11.0.4_1.3.2_2.13.1
    user: sbtuser
    commands:
      - sbt -Dsbt.color=true -Dsbt.supershell=false clean assembly
